### ISSUE TITLE
Installation Failed?

### ISSUE THREAD

**Issue by Nzzyme** [henry-richard7/Kodi-ZEE5-TV-Addon#1]
Hello, I downloaded the add-on zip file to my Android TV box and then selected the option "Install from zip file" in Kodi for Android and after few seconds, I get the message that it has failed. Am I doing something wrong? Please advise.

**Comment by henry-richard7** [comment]
Which version of kodi your using?

**Comment by Nzzyme** [comment]
Please ignore my above post. I tried again and it worked. Thank you for the quick response though.

**Comment by henry-richard7** [comment]
Glad its working
